@startuml

skinparam handwritten true
skinparam monochrome true
left to right direction

actor consumer
database "cdw"
database "id-store" as iddb
rectangle "argonaut"
rectangle "ids"
rectangle "mr-anderson" as mra

consumer -(0- argonaut
argonaut -(0- mra
mra -- cdw
mra -(0- ids
ids -- iddb

@enduml
